const JobPosting = require('../models/JobPosting');

// Curated high-caliber predefined job postings (~72 jobs) across diverse companies, roles, types, and global locations
const CURATED_JOBS = [
  {
    title: 'Senior Full Stack Engineer (React / Node / TypeScript)',
    company: 'Stripe',
    companyLogo: 'https://logo.clearbit.com/stripe.com',
    companyWebsite: 'https://stripe.com',
    location: 'Remote - Worldwide',
    salary: '$140,000 - $190,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'senior',
    requiredSkills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'GraphQL', 'AWS'],
    tags: ['FinTech', 'High Growth', 'Remote First'],
    description: 'Build mission-critical payment infrastructure and delightful merchant portals powering millions of internet businesses globally. You will design scalable microservices and architect responsive user interfaces.',
    jobUrl: 'https://stripe.com/jobs',
    applicantCount: 42,
    isActive: true
  },
  {
    title: 'Frontend UI/UX Architect (Next.js & Design Systems)',
    company: 'Vercel',
    companyLogo: 'https://logo.clearbit.com/vercel.com',
    companyWebsite: 'https://vercel.com',
    location: 'Remote - North America / EU',
    salary: '$130,000 - $175,000 / yr',
    jobType: 'full_time',
    category: 'Frontend',
    experienceLevel: 'mid',
    requiredSkills: ['React', 'Next.js', 'TypeScript', 'TailwindCSS', 'Framer Motion', 'Web Performance'],
    tags: ['Design Systems', 'Developer Tools', 'Cloud'],
    description: 'Craft world-class developer experiences and dashboard interfaces for millions of web developers. Help push the frontier of modern frontend frameworks and edge rendering.',
    jobUrl: 'https://vercel.com/careers',
    applicantCount: 89,
    isActive: true
  },
  {
    title: 'Freelance AI Web Application Specialist',
    company: 'Anthropic',
    companyLogo: 'https://logo.clearbit.com/anthropic.com',
    companyWebsite: 'https://anthropic.com',
    location: 'Remote',
    salary: '$95 - $140 / hr',
    jobType: 'freelance',
    category: 'AI & Data',
    experienceLevel: 'senior',
    requiredSkills: ['Python', 'FastAPI', 'React', 'Prompt Engineering', 'LangChain', 'Vector DBs'],
    tags: ['Generative AI', 'Freelance Contract', 'High Rate'],
    description: 'Collaborate on prototype AI assistant interfaces, interactive sandbox environments, and LLM benchmarking platforms. Flexible hourly contract with immediate kickoff.',
    jobUrl: 'https://anthropic.com/careers',
    applicantCount: 64,
    isActive: true
  },
  {
    title: 'Backend Systems & Distributed DB Engineer',
    company: 'MongoDB',
    companyLogo: 'https://logo.clearbit.com/mongodb.com',
    companyWebsite: 'https://mongodb.com',
    location: 'Bengaluru, India (Hybrid)',
    salary: '₹28,00,000 - ₹42,00,000 / yr',
    jobType: 'full_time',
    category: 'Backend',
    experienceLevel: 'mid',
    requiredSkills: ['Go', 'C++', 'Distributed Systems', 'MongoDB', 'Kafka', 'Docker'],
    tags: ['Database', 'Core Infrastructure', 'Hybrid'],
    description: 'Work on database kernel optimizations, cloud atlas auto-sharding algorithms, and high-throughput query execution pipelines.',
    jobUrl: 'https://mongodb.com/careers',
    applicantCount: 31,
    isActive: true
  },
  {
    title: 'Mobile App Developer (React Native & Flutter)',
    company: 'Swiggy',
    companyLogo: 'https://logo.clearbit.com/swiggy.com',
    companyWebsite: 'https://swiggy.com',
    location: 'Bengaluru, India',
    salary: '₹22,00,000 - ₹35,00,000 / yr',
    jobType: 'full_time',
    category: 'Mobile',
    experienceLevel: 'mid',
    requiredSkills: ['React Native', 'TypeScript', 'Redux Toolkit', 'Mobile Performance', 'Native Android/iOS'],
    tags: ['Hyperlocal', 'Consumer Tech', 'High Scale'],
    description: 'Ship high-performance consumer app experiences serving over 150 million orders monthly. Optimize startup time, frame rates, and offline resiliency.',
    jobUrl: 'https://swiggy.com/careers',
    applicantCount: 57,
    isActive: true
  },
  {
    title: 'Contract Web3 & Smart Contracts Auditor',
    company: 'Polygon Labs',
    companyLogo: 'https://logo.clearbit.com/polygon.technology',
    companyWebsite: 'https://polygon.technology',
    location: 'Remote',
    salary: '$80 - $125 / hr',
    jobType: 'contract',
    category: 'Security & Web3',
    experienceLevel: 'senior',
    requiredSkills: ['Solidity', 'Rust', 'EVM', 'Smart Contract Security', 'Foundry'],
    tags: ['Web3', 'Contract', 'ZK Rollups'],
    description: 'Perform rigorous security audits, formal verification, and gas optimization for next-generation zkEVM protocols and bridges.',
    jobUrl: 'https://polygon.technology/careers',
    applicantCount: 19,
    isActive: true
  },
  {
    title: 'Software Engineering Graduate Intern (Summer 2026)',
    company: 'Microsoft',
    companyLogo: 'https://logo.clearbit.com/microsoft.com',
    companyWebsite: 'https://microsoft.com',
    location: 'Hyderabad / Bengaluru, India',
    salary: '₹85,000 / month Stipend',
    jobType: 'internship',
    category: 'Engineering',
    experienceLevel: 'fresher',
    requiredSkills: ['Data Structures & Algorithms', 'C++', 'Java', 'Python', 'Object Oriented Programming', 'Git'],
    tags: ['Internship', 'Mentorship', 'PPO Opportunity'],
    description: 'Join Azure or Office 365 core teams for an intensive 3-6 month internship. Work with world-class mentors, solve real customer challenges, and gain hands-on production experience.',
    jobUrl: 'https://careers.microsoft.com',
    applicantCount: 184,
    isActive: true
  },
  {
    title: 'Cloud DevOps & Kubernetes Engineer',
    company: 'Razorpay',
    companyLogo: 'https://logo.clearbit.com/razorpay.com',
    companyWebsite: 'https://razorpay.com',
    location: 'Bengaluru, India',
    salary: '₹24,00,000 - ₹38,00,000 / yr',
    jobType: 'full_time',
    category: 'DevOps & Cloud',
    experienceLevel: 'senior',
    requiredSkills: ['AWS', 'Kubernetes', 'Terraform', 'CI/CD', 'Prometheus', 'Golang'],
    tags: ['FinTech', 'DevOps', 'Cloud Native'],
    description: 'Maintain 99.999% availability across payment processing clusters handling billions in monthly transactions. Build automated multi-region failover infrastructure.',
    jobUrl: 'https://razorpay.com/jobs',
    applicantCount: 28,
    isActive: true
  },
  {
    title: 'Freelance Creative Front-end Developer',
    company: 'Figma',
    companyLogo: 'https://logo.clearbit.com/figma.com',
    companyWebsite: 'https://figma.com',
    location: 'Remote',
    salary: '$90 - $130 / hr',
    jobType: 'freelance',
    category: 'Frontend',
    experienceLevel: 'mid',
    requiredSkills: ['Three.js', 'WebGL', 'React', 'GSAP', 'CSS Animations', 'Canvas API'],
    tags: ['Creative Tech', 'Interactive 3D', 'Remote'],
    description: 'Build mind-blowing interactive showcase websites, 3D interactive marketing micro-sites, and dynamic WebGL shaders for brand releases.',
    jobUrl: 'https://figma.com/careers',
    applicantCount: 73,
    isActive: true
  },
  {
    title: 'Associate Product Engineer (React / Python)',
    company: 'Notion',
    companyLogo: 'https://logo.clearbit.com/notion.so',
    companyWebsite: 'https://notion.so',
    location: 'Remote - Global',
    salary: '$110,000 - $145,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'junior',
    requiredSkills: ['React', 'TypeScript', 'Python', 'SQLite', 'IndexedDB', 'REST APIs'],
    tags: ['Productivity', 'Collaborative', 'High Impact'],
    description: 'Craft features for Notion calendar, offline synchronization, and workspace collaboration tools used by tens of millions of teams worldwide.',
    jobUrl: 'https://notion.so/careers',
    applicantCount: 112,
    isActive: true
  },
  {
    title: 'AI Research Engineer (LLM Alignment & RAG)',
    company: 'OpenAI',
    companyLogo: 'https://logo.clearbit.com/openai.com',
    companyWebsite: 'https://openai.com',
    location: 'San Francisco, CA / Remote',
    salary: '$190,000 - $260,000 / yr',
    jobType: 'full_time',
    category: 'AI & Data',
    experienceLevel: 'lead',
    requiredSkills: ['PyTorch', 'Python', 'Transformers', 'CUDA', 'Distributed Training', 'RLHF'],
    tags: ['Frontier AI', 'Deep Learning', 'S-Rank'],
    description: 'Work on post-training alignment, reinforcement learning from human feedback, and optimizing memory bandwidth for large multimodal models.',
    jobUrl: 'https://openai.com/careers',
    applicantCount: 245,
    isActive: true
  },
  {
    title: 'Contract Full Stack MERN Developer',
    company: 'Uber',
    companyLogo: 'https://logo.clearbit.com/uber.com',
    companyWebsite: 'https://uber.com',
    location: 'Remote / Hyderabad',
    salary: '$60 - $90 / hr',
    jobType: 'contract',
    category: 'Engineering',
    experienceLevel: 'mid',
    requiredSkills: ['MongoDB', 'Express', 'React', 'Node.js', 'Redis', 'Kafka'],
    tags: ['Mobility', 'MERN Stack', 'Contract'],
    description: 'Develop internal driver operations portals and fleet management analytics dashboards. 6-month contract with extension possibility.',
    jobUrl: 'https://uber.com/careers',
    applicantCount: 46,
    isActive: true
  },
  {
    title: 'Staff Software Engineer - Distributed Cloud Systems',
    company: 'Google',
    companyLogo: 'https://logo.clearbit.com/google.com',
    companyWebsite: 'https://google.com',
    location: 'Mountain View, CA / Hyderabad, India',
    salary: '$210,000 - $290,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'lead',
    requiredSkills: ['Go', 'C++', 'Kubernetes', 'Spanner', 'gRPC', 'Distributed Consensus'],
    tags: ['Google Cloud', 'Distributed Systems', 'Hyper Scale'],
    description: 'Architect planetary scale infrastructure for Google Cloud Platform services. Lead cross-functional engineering initiatives spanning data center networking and high-resiliency storage.',
    jobUrl: 'https://careers.google.com',
    applicantCount: 178,
    isActive: true
  },
  {
    title: 'Senior iOS Software Engineer (Swift / SwiftUI)',
    company: 'Apple',
    companyLogo: 'https://logo.clearbit.com/apple.com',
    companyWebsite: 'https://apple.com',
    location: 'Cupertino, CA / Remote',
    salary: '$165,000 - $225,000 / yr',
    jobType: 'full_time',
    category: 'Mobile',
    experienceLevel: 'senior',
    requiredSkills: ['Swift', 'SwiftUI', 'Combine', 'CoreData', 'Metal', 'iOS SDK'],
    tags: ['iOS', 'Hardware-Software', 'Consumer Ecosystem'],
    description: 'Shape next-generation iOS user experiences and system frameworks. Collaborate directly with Apple Human Interface design teams on polished tactile interactions.',
    jobUrl: 'https://jobs.apple.com',
    applicantCount: 92,
    isActive: true
  },
  {
    title: 'AWS Cloud Infrastructure & Solutions Architect',
    company: 'Amazon',
    companyLogo: 'https://logo.clearbit.com/amazon.com',
    companyWebsite: 'https://amazon.com',
    location: 'Seattle, WA / Bengaluru, India',
    salary: '$150,000 - $205,000 / yr',
    jobType: 'full_time',
    category: 'DevOps & Cloud',
    experienceLevel: 'senior',
    requiredSkills: ['AWS Lambda', 'DynamoDB', 'Terraform', 'CloudFormation', 'Python', 'IAM'],
    tags: ['AWS', 'Serverless', 'Cloud Architect'],
    description: 'Design resilient multi-region architectures for Fortune 500 enterprise migrations. Optimize latency, reliability, and security for millions of concurrent requests.',
    jobUrl: 'https://amazon.jobs',
    applicantCount: 134,
    isActive: true
  },
  {
    title: 'Senior React & VR Core Developer',
    company: 'Meta',
    companyLogo: 'https://logo.clearbit.com/meta.com',
    companyWebsite: 'https://meta.com',
    location: 'Menlo Park, CA / Remote',
    salary: '$175,000 - $240,000 / yr',
    jobType: 'full_time',
    category: 'Frontend',
    experienceLevel: 'senior',
    requiredSkills: ['React', 'TypeScript', 'WebXR', 'Three.js', 'State Management', 'Performance Profiling'],
    tags: ['Spatial Computing', 'WebXR', 'Social Platform'],
    description: 'Build fluid 3D spatial web applications and core UI toolkits for Quest VR/AR devices and modern web surfaces.',
    jobUrl: 'https://metacareers.com',
    applicantCount: 88,
    isActive: true
  },
  {
    title: 'Senior UI Platform Engineer (Micro-frontends)',
    company: 'Netflix',
    companyLogo: 'https://logo.clearbit.com/netflix.com',
    companyWebsite: 'https://netflix.com',
    location: 'Los Gatos, CA / Remote',
    salary: '$195,000 - $275,000 / yr',
    jobType: 'full_time',
    category: 'Frontend',
    experienceLevel: 'senior',
    requiredSkills: ['React', 'TypeScript', 'Webpack Module Federation', 'GraphQL', 'A/B Testing', 'Node.js'],
    tags: ['Streaming', 'Platform Engineering', 'High Velocity'],
    description: 'Scale the client foundation powering Netflix web and TV client applications across 260+ million subscribers worldwide.',
    jobUrl: 'https://jobs.netflix.com',
    applicantCount: 110,
    isActive: true
  },
  {
    title: 'Deep Learning & CUDA Performance Engineer',
    company: 'NVIDIA',
    companyLogo: 'https://logo.clearbit.com/nvidia.com',
    companyWebsite: 'https://nvidia.com',
    location: 'Santa Clara, CA / Pune, India',
    salary: '$180,000 - $250,000 / yr',
    jobType: 'full_time',
    category: 'AI & Data',
    experienceLevel: 'senior',
    requiredSkills: ['CUDA', 'C++', 'PyTorch', 'TensorRT', 'GPU Kernel Optimization', 'Parallel Computing'],
    tags: ['GPU Acceleration', 'AI Silicon', 'Hardware Performance'],
    description: 'Optimize cutting-edge LLM training and inference pipelines on Blackwell and Hopper GPU clusters. Implement custom CUDA kernels for extreme throughput.',
    jobUrl: 'https://nvidia.com/careers',
    applicantCount: 95,
    isActive: true
  },
  {
    title: 'Embedded Systems & Autonomous Vehicle Software Engineer',
    company: 'Tesla',
    companyLogo: 'https://logo.clearbit.com/tesla.com',
    companyWebsite: 'https://tesla.com',
    location: 'Austin, TX / Palo Alto, CA',
    salary: '$160,000 - $220,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'mid',
    requiredSkills: ['C++', 'Rust', 'RTOS', 'CAN Bus', 'Linux Kernel', 'Control Systems'],
    tags: ['Autopilot', 'Automotive', 'Embedded Systems'],
    description: 'Develop low-latency sensor ingestion, telemetry processing, and embedded firmware for Full Self-Driving (FSD) vehicle computing computers.',
    jobUrl: 'https://tesla.com/careers',
    applicantCount: 78,
    isActive: true
  },
  {
    title: 'Full Stack Product Engineer (Growth & Bookings)',
    company: 'Airbnb',
    companyLogo: 'https://logo.clearbit.com/airbnb.com',
    companyWebsite: 'https://airbnb.com',
    location: 'San Francisco, CA / Remote',
    salary: '$155,000 - $210,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'mid',
    requiredSkills: ['React', 'TypeScript', 'Java', 'GraphQL', 'MySQL', 'Design Systems'],
    tags: ['Travel Tech', 'Product Engineering', 'Consumer Product'],
    description: 'Build intuitive booking funnels, host management tools, and seamless multilingual checkout experiences across 190+ countries.',
    jobUrl: 'https://careers.airbnb.com',
    applicantCount: 104,
    isActive: true
  },
  {
    title: 'Distributed Data Platform Engineer (Spark / Lakehouse)',
    company: 'Databricks',
    companyLogo: 'https://logo.clearbit.com/databricks.com',
    companyWebsite: 'https://databricks.com',
    location: 'Remote - North America / EU',
    salary: '$170,000 - $235,000 / yr',
    jobType: 'full_time',
    category: 'AI & Data',
    experienceLevel: 'senior',
    requiredSkills: ['Scala', 'Java', 'Apache Spark', 'Delta Lake', 'Distributed Storage', 'Rust'],
    tags: ['Lakehouse', 'Big Data', 'Cloud Native'],
    description: 'Innovate on Delta Lake query acceleration, autonomous query planning, and scalable lakehouse engine kernels processing exabytes of enterprise data.',
    jobUrl: 'https://databricks.com/company/careers',
    applicantCount: 61,
    isActive: true
  },
  {
    title: 'Freelance Senior UI/UX & Design Systems Engineer',
    company: 'Canva',
    companyLogo: 'https://logo.clearbit.com/canva.com',
    companyWebsite: 'https://canva.com',
    location: 'Remote - APAC / Worldwide',
    salary: '$85 - $120 / hr',
    jobType: 'freelance',
    category: 'Frontend',
    experienceLevel: 'senior',
    requiredSkills: ['React', 'TypeScript', 'Storybook', 'Figma Tokens', 'Accessibility WCAG', 'CSS Architecture'],
    tags: ['Design Systems', 'Freelance Contract', 'Design Tools'],
    description: 'Help scale Canva design tokens and reusable component libraries. Deliver pixel-perfect, accessible components for millions of creative users.',
    jobUrl: 'https://canva.com/careers',
    applicantCount: 52,
    isActive: true
  },
  {
    title: 'Backend Infrastructure Engineer (Audio Streaming)',
    company: 'Spotify',
    companyLogo: 'https://logo.clearbit.com/spotify.com',
    companyWebsite: 'https://spotify.com',
    location: 'Stockholm, Sweden / London, UK / Remote',
    salary: '$135,000 - $180,000 / yr',
    jobType: 'full_time',
    category: 'Backend',
    experienceLevel: 'mid',
    requiredSkills: ['Java', 'Python', 'GCP', 'Kafka', 'Cassandra', 'Microservices'],
    tags: ['Audio Streaming', 'Global Scale', 'Finest Culture'],
    description: 'Engineer high-fidelity audio content delivery pipelines, real-time recommendation caching, and social playback sync for 600M+ active listeners.',
    jobUrl: 'https://lifeatspotify.com',
    applicantCount: 97,
    isActive: true
  },
  {
    title: 'Real-time Voice & WebRTC Systems Engineer (Elixir / Rust)',
    company: 'Discord',
    companyLogo: 'https://logo.clearbit.com/discord.com',
    companyWebsite: 'https://discord.com',
    location: 'San Francisco, CA / Remote',
    salary: '$160,000 - $215,000 / yr',
    jobType: 'full_time',
    category: 'Backend',
    experienceLevel: 'senior',
    requiredSkills: ['Elixir', 'Rust', 'WebRTC', 'Networking UDP/TCP', 'Distributed State', 'Live Streaming'],
    tags: ['Real-time Systems', 'WebRTC', 'Gaming & Communities'],
    description: 'Architect ultra-low latency voice and video packet routing systems supporting millions of simultaneous voice rooms worldwide.',
    jobUrl: 'https://discord.com/careers',
    applicantCount: 71,
    isActive: true
  },
  {
    title: 'Senior Frontend Engineer (Sync Engine & WebGL)',
    company: 'Linear',
    companyLogo: 'https://logo.clearbit.com/linear.app',
    companyWebsite: 'https://linear.app',
    location: 'Remote - Worldwide',
    salary: '$140,000 - $190,000 / yr',
    jobType: 'full_time',
    category: 'Frontend',
    experienceLevel: 'senior',
    requiredSkills: ['React', 'TypeScript', 'IndexedDB', 'CRDTs', 'CSS Animation', 'WebSockets'],
    tags: ['Productivity', 'Craftsmanship', 'High Performance'],
    description: 'Work on our industry-leading local-first sync engine, lightning-quick keyboard workflows, and buttery smooth 60fps web UI rendering.',
    jobUrl: 'https://linear.app/careers',
    applicantCount: 126,
    isActive: true
  },
  {
    title: 'Open-source Database & Elixir Systems Engineer',
    company: 'Supabase',
    companyLogo: 'https://logo.clearbit.com/supabase.com',
    companyWebsite: 'https://supabase.com',
    location: 'Remote - Worldwide',
    salary: '$125,000 - $170,000 / yr',
    jobType: 'full_time',
    category: 'Backend',
    experienceLevel: 'mid',
    requiredSkills: ['Elixir', 'PostgreSQL', 'Go', 'Docker', 'Realtime', 'Open Source'],
    tags: ['Open Source', 'Postgres', 'Backend as a Service'],
    description: 'Build open-source Firebase alternatives using Postgres, Elixir Realtime gateways, and automated database clustering.',
    jobUrl: 'https://supabase.com/careers',
    applicantCount: 84,
    isActive: true
  },
  {
    title: 'Cloud Infrastructure & Terraform Core Engineer (Go)',
    company: 'HashiCorp',
    companyLogo: 'https://logo.clearbit.com/hashicorp.com',
    companyWebsite: 'https://hashicorp.com',
    location: 'Remote - US / EU',
    salary: '$145,000 - $195,000 / yr',
    jobType: 'full_time',
    category: 'DevOps & Cloud',
    experienceLevel: 'senior',
    requiredSkills: ['Go', 'Terraform', 'Vault', 'Consul', 'Cloud APIs', 'Distributed Systems'],
    tags: ['Infrastructure as Code', 'Cloud Security', 'Open Source'],
    description: 'Contribute to Terraform core provider ecosystem and Vault secrets management engines powering modern cloud infrastructure.',
    jobUrl: 'https://hashicorp.com/careers',
    applicantCount: 49,
    isActive: true
  },
  {
    title: 'Principal Database Kernel Engineer (C++ / Rust)',
    company: 'Snowflake',
    companyLogo: 'https://logo.clearbit.com/snowflake.com',
    companyWebsite: 'https://snowflake.com',
    location: 'San Mateo, CA / Bellevue, WA',
    salary: '$200,000 - $280,000 / yr',
    jobType: 'full_time',
    category: 'Backend',
    experienceLevel: 'lead',
    requiredSkills: ['C++', 'Rust', 'SQL Query Execution', 'SIMD Vectorization', 'Cloud Object Storage', 'Concurrency'],
    tags: ['Cloud Data Warehouse', 'Database Kernels', 'Extreme Performance'],
    description: 'Design next-generation vectorized query engines, compute-storage separation layers, and high-performance columnar file formats.',
    jobUrl: 'https://careers.snowflake.com',
    applicantCount: 38,
    isActive: true
  },
  {
    title: 'Container Runtime & Developer Platform Engineer',
    company: 'Docker',
    companyLogo: 'https://logo.clearbit.com/docker.com',
    companyWebsite: 'https://docker.com',
    location: 'Remote - North America / EU',
    salary: '$135,000 - $185,000 / yr',
    jobType: 'full_time',
    category: 'DevOps & Cloud',
    experienceLevel: 'mid',
    requiredSkills: ['Go', 'Docker Engine', 'containerd', 'Linux Namespaces', 'CI/CD', 'Desktop App'],
    tags: ['Containers', 'Developer Tooling', 'Virtualization'],
    description: 'Improve Docker Desktop performance on Apple Silicon and Windows WSL2. Architect seamless container build caches and image registries.',
    jobUrl: 'https://docker.com/careers',
    applicantCount: 67,
    isActive: true
  },
  {
    title: 'Site Reliability & Observability Platform Engineer',
    company: 'Datadog',
    companyLogo: 'https://logo.clearbit.com/datadoghq.com',
    companyWebsite: 'https://datadoghq.com',
    location: 'New York, NY / Paris, France / Remote',
    salary: '$150,000 - $205,000 / yr',
    jobType: 'full_time',
    category: 'DevOps & Cloud',
    experienceLevel: 'senior',
    requiredSkills: ['Go', 'Python', 'Kubernetes', 'APM', 'Distributed Tracing', 'Terraform'],
    tags: ['Observability', 'Monitoring', 'High Scale'],
    description: 'Build high-throughput metric ingestion gateways processing trillions of datapoints daily from global cloud infrastructure.',
    jobUrl: 'https://datadoghq.com/careers',
    applicantCount: 55,
    isActive: true
  },
  {
    title: 'Edge Network & Workers Platform Engineer (Rust / WASM)',
    company: 'Cloudflare',
    companyLogo: 'https://logo.clearbit.com/cloudflare.com',
    companyWebsite: 'https://cloudflare.com',
    location: 'Austin, TX / London, UK / Remote',
    salary: '$145,000 - $200,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'senior',
    requiredSkills: ['Rust', 'WebAssembly', 'V8 Isolates', 'BGP Routing', 'HTTP/3', 'C++'],
    tags: ['Edge Computing', 'Serverless', 'DDoS Protection'],
    description: 'Empower developers to run sub-millisecond edge code on Cloudflare global anycast network across 300+ cities.',
    jobUrl: 'https://cloudflare.com/careers',
    applicantCount: 82,
    isActive: true
  },
  {
    title: 'Senior Backend Engineer (Actions & CI/CD Pipeline)',
    company: 'GitHub',
    companyLogo: 'https://logo.clearbit.com/github.com',
    companyWebsite: 'https://github.com',
    location: 'Remote - Worldwide',
    salary: '$140,000 - $190,000 / yr',
    jobType: 'full_time',
    category: 'Backend',
    experienceLevel: 'senior',
    requiredSkills: ['Ruby on Rails', 'Go', 'Azure', 'Kubernetes', 'MySQL', 'GraphQL'],
    tags: ['Developer Platform', 'CI/CD', 'Git'],
    description: 'Engineer GitHub Actions workflow runners and repository security scanning engines used by 100+ million software developers.',
    jobUrl: 'https://github.com/about/careers',
    applicantCount: 140,
    isActive: true
  },
  {
    title: 'Remote Ruby on Rails & Go Platform Engineer',
    company: 'GitLab',
    companyLogo: 'https://logo.clearbit.com/gitlab.com',
    companyWebsite: 'https://gitlab.com',
    location: 'Remote - Worldwide (All-Remote)',
    salary: '$130,000 - $175,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'mid',
    requiredSkills: ['Ruby on Rails', 'Go', 'Vue.js', 'PostgreSQL', 'Redis', 'Gitaly'],
    tags: ['DevSecOps', 'All-Remote', 'Open Core'],
    description: 'Help develop GitLab single DevOps platform application. Optimize Gitaly git RPC services and merge request collaboration pipelines.',
    jobUrl: 'https://about.gitlab.com/jobs',
    applicantCount: 76,
    isActive: true
  },
  {
    title: 'Cloud Jira Platform & Distributed Microservices Lead',
    company: 'Atlassian',
    companyLogo: 'https://logo.clearbit.com/atlassian.com',
    companyWebsite: 'https://atlassian.com',
    location: 'Bengaluru, India / Sydney, Australia',
    salary: '₹35,00,000 - ₹52,00,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'lead',
    requiredSkills: ['Java', 'Spring Boot', 'React', 'AWS', 'DynamoDB', 'Microservices'],
    tags: ['Workplace Collaboration', 'Enterprise SaaS', 'Teamwork'],
    description: 'Lead engineering pods modernizing Jira Cloud architecture for large-scale enterprise organizations with zero downtime migrations.',
    jobUrl: 'https://atlassian.com/company/careers',
    applicantCount: 45,
    isActive: true
  },
  {
    title: 'Forward Deployed Software Engineer (Foundry / Data)',
    company: 'Palantir',
    companyLogo: 'https://logo.clearbit.com/palantir.com',
    companyWebsite: 'https://palantir.com',
    location: 'New York, NY / London, UK',
    salary: '$150,000 - $210,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'mid',
    requiredSkills: ['TypeScript', 'Python', 'Java', 'Data Pipelines', 'Enterprise Analytics', 'SQL'],
    tags: ['Defense & Enterprise', 'Big Data', 'High Impact'],
    description: 'Deploy mission-critical data operating systems directly with frontline customers in healthcare, aviation, and national defense.',
    jobUrl: 'https://palantir.com/careers',
    applicantCount: 63,
    isActive: true
  },
  {
    title: 'Machine Learning Engineer (Visual Search & Recommendation)',
    company: 'Pinterest',
    companyLogo: 'https://logo.clearbit.com/pinterest.com',
    companyWebsite: 'https://pinterest.com',
    location: 'San Francisco, CA / Remote',
    salary: '$160,000 - $220,000 / yr',
    jobType: 'full_time',
    category: 'AI & Data',
    experienceLevel: 'senior',
    requiredSkills: ['PyTorch', 'Python', 'Computer Vision', 'Vector Search (HNSW)', 'Graph Neural Networks', 'AWS'],
    tags: ['Visual Search', 'ML Recommendations', 'Social Discovery'],
    description: 'Train visual embedding models and GraphSAGE neural networks indexing billions of images and shopping items.',
    jobUrl: 'https://pinterestcareers.com',
    applicantCount: 77,
    isActive: true
  },
  {
    title: 'Real-time Messaging Infrastructure Engineer',
    company: 'Slack',
    companyLogo: 'https://logo.clearbit.com/slack.com',
    companyWebsite: 'https://slack.com',
    location: 'San Francisco, CA / Remote',
    salary: '$155,000 - $210,000 / yr',
    jobType: 'full_time',
    category: 'Backend',
    experienceLevel: 'senior',
    requiredSkills: ['Java', 'PHP/Hack', 'Kafka', 'MySQL', 'WebSockets', 'Distributed Caching'],
    tags: ['Enterprise Messaging', 'Realtime', 'Productivity'],
    description: 'Build high-availability message brokers delivering hundreds of millions of conversations per second without packet drop.',
    jobUrl: 'https://slack.com/careers',
    applicantCount: 85,
    isActive: true
  },
  {
    title: 'High-performance Video & Media Streaming Engineer',
    company: 'Zoom',
    companyLogo: 'https://logo.clearbit.com/zoom.us',
    companyWebsite: 'https://zoom.us',
    location: 'San Jose, CA / Remote',
    salary: '$145,000 - $195,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'senior',
    requiredSkills: ['C++', 'AV1 Codec', 'H.264/H.265', 'RTP/RTCP', 'Noise Cancellation AI', 'Multi-platform SDK'],
    tags: ['Video Conferencing', 'Media Streaming', 'Audio Processing'],
    description: 'Optimize adaptive bitrate video pipelines, real-time background blur filters, and low-bandwidth audio synthesis.',
    jobUrl: 'https://zoom.us/careers',
    applicantCount: 59,
    isActive: true
  },
  {
    title: 'Senior Ruby / React Commerce Engine Architect',
    company: 'Shopify',
    companyLogo: 'https://logo.clearbit.com/shopify.com',
    companyWebsite: 'https://shopify.com',
    location: 'Remote - Americas / EMEA',
    salary: '$150,000 - $205,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'senior',
    requiredSkills: ['Ruby on Rails', 'React', 'TypeScript', 'GraphQL', 'MySQL', 'Kafka'],
    tags: ['E-Commerce', 'Merchant Success', 'High Traffic'],
    description: 'Architect the checkout infrastructure handling Flash Sales and Black Friday Cyber Monday peak traffic of $40k+ orders/minute.',
    jobUrl: 'https://shopify.com/careers',
    applicantCount: 94,
    isActive: true
  },
  {
    title: 'Senior Backend Engineer (High-throughput Ordering)',
    company: 'Zomato',
    companyLogo: 'https://logo.clearbit.com/zomato.com',
    companyWebsite: 'https://zomato.com',
    location: 'Gurugram / Delhi NCR, India',
    salary: '₹26,00,000 - ₹40,00,000 / yr',
    jobType: 'full_time',
    category: 'Backend',
    experienceLevel: 'senior',
    requiredSkills: ['Go', 'Node.js', 'Redis', 'PostgreSQL', 'Kafka', 'Microservices'],
    tags: ['Food Delivery', 'Blinkit Quick Commerce', 'High QPS'],
    description: 'Power real-time rider dispatch algorithms, lightning quick menu searching, and millisecond cart validation for millions of daily orders.',
    jobUrl: 'https://zomato.com/careers',
    applicantCount: 79,
    isActive: true
  },
  {
    title: 'Mobile Platform Lead (React Native / Native Android)',
    company: 'CRED',
    companyLogo: 'https://logo.clearbit.com/cred.club',
    companyWebsite: 'https://cred.club',
    location: 'Bengaluru, India',
    salary: '₹32,00,000 - ₹50,00,000 / yr',
    jobType: 'full_time',
    category: 'Mobile',
    experienceLevel: 'lead',
    requiredSkills: ['React Native', 'Kotlin', 'Swift', 'Custom Animations', 'FinTech Security', 'App Performance'],
    tags: ['FinTech', 'Neo-Banking', 'UI Polish'],
    description: 'Drive high-craft mobile experiences, gamified reward systems, and biometric credit card statement analytics for India’s premier financial community.',
    jobUrl: 'https://cred.club/careers',
    applicantCount: 68,
    isActive: true
  },
  {
    title: 'Senior Big Data Engineer (E-commerce Fulfillment)',
    company: 'Flipkart',
    companyLogo: 'https://logo.clearbit.com/flipkart.com',
    companyWebsite: 'https://flipkart.com',
    location: 'Bengaluru, India',
    salary: '₹28,00,000 - ₹44,00,000 / yr',
    jobType: 'full_time',
    category: 'AI & Data',
    experienceLevel: 'senior',
    requiredSkills: ['Apache Spark', 'Hadoop', 'Java', 'Flink', 'Kafka', 'Hive'],
    tags: ['E-Commerce', 'Supply Chain', 'Big Data'],
    description: 'Build predictive logistics and inventory replenishment engines orchestrating millions of packages across 10,000+ pin codes in India.',
    jobUrl: 'https://flipkartcareers.com',
    applicantCount: 83,
    isActive: true
  },
  {
    title: 'Full Stack Product Developer (Social Commerce)',
    company: 'Meesho',
    companyLogo: 'https://logo.clearbit.com/meesho.com',
    companyWebsite: 'https://meesho.com',
    location: 'Bengaluru, India',
    salary: '₹22,00,000 - ₹36,00,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'mid',
    requiredSkills: ['React', 'Node.js', 'Java', 'MongoDB', 'AWS', 'Redis'],
    tags: ['E-Commerce', 'Social Commerce', 'Hyper Growth'],
    description: 'Empower over 15 million micro-entrepreneurs across Tier 2+ India with localized catalog sharing, order tracking, and supplier payouts.',
    jobUrl: 'https://meesho.io/careers',
    applicantCount: 65,
    isActive: true
  },
  {
    title: 'Principal Payments Backend Engineer (Fintech Scale)',
    company: 'PhonePe',
    companyLogo: 'https://logo.clearbit.com/phonepe.com',
    companyWebsite: 'https://phonepe.com',
    location: 'Bengaluru / Pune, India',
    salary: '₹38,00,000 - ₹58,00,000 / yr',
    jobType: 'full_time',
    category: 'Backend',
    experienceLevel: 'lead',
    requiredSkills: ['Java', 'Spring Boot', 'Cassandra', 'Kafka', 'Distributed Transactions', 'UPI Protocols'],
    tags: ['UPI Payments', 'Fintech Infrastructure', 'High TPS'],
    description: 'Maintain the backbone processing over 45% of India’s UPI transactions. Lead high-throughput payment switch architectures.',
    jobUrl: 'https://phonepe.com/careers',
    applicantCount: 51,
    isActive: true
  },
  {
    title: 'High-Frequency Trading Platform Engineer (Go / Python)',
    company: 'Zerodha',
    companyLogo: 'https://logo.clearbit.com/zerodha.com',
    companyWebsite: 'https://zerodha.com',
    location: 'Bengaluru, India',
    salary: '₹25,00,000 - ₹40,00,000 / yr',
    jobType: 'full_time',
    category: 'Backend',
    experienceLevel: 'mid',
    requiredSkills: ['Go', 'Python', 'PostgreSQL', 'Redis', 'WebSockets', 'Linux Sockets'],
    tags: ['Kite Trading', 'Fintech', 'Bootstrapped Tech'],
    description: 'Work on Kite order matching engine, live stock market tick broadcasts, and zero-latency margin computation engines.',
    jobUrl: 'https://zerodha.com/careers',
    applicantCount: 115,
    isActive: true
  },
  {
    title: 'Developer Experience & API Tooling Architect',
    company: 'Postman',
    companyLogo: 'https://logo.clearbit.com/postman.com',
    companyWebsite: 'https://postman.com',
    location: 'Bengaluru / San Francisco / Remote',
    salary: '₹30,00,000 - ₹46,00,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'senior',
    requiredSkills: ['TypeScript', 'Node.js', 'Electron', 'REST APIs', 'OpenAPI Spec', 'GraphQL'],
    tags: ['API Platform', 'Developer Productivity', 'Global SaaS'],
    description: 'Build collaboration features, mock servers, and automated testing workspaces used by 30+ million developers worldwide.',
    jobUrl: 'https://postman.com/careers',
    applicantCount: 72,
    isActive: true
  },
  {
    title: 'Cloud Automation & Device Infrastructure Engineer',
    company: 'BrowserStack',
    companyLogo: 'https://logo.clearbit.com/browserstack.com',
    companyWebsite: 'https://browserstack.com',
    location: 'Mumbai / Bengaluru / Remote',
    salary: '₹24,00,000 - ₹38,00,000 / yr',
    jobType: 'full_time',
    category: 'DevOps & Cloud',
    experienceLevel: 'mid',
    requiredSkills: ['Node.js', 'Ruby', 'Selenium', 'Appium', 'Docker', 'Linux Virtualization'],
    tags: ['Testing Cloud', 'Real Device Farm', 'Dev Tools'],
    description: 'Scale physical and virtual mobile device clouds running millions of automated browser tests daily for global software teams.',
    jobUrl: 'https://browserstack.com/careers',
    applicantCount: 48,
    isActive: true
  },
  {
    title: '5G Cloud Core & Edge Systems Engineer',
    company: 'Jio Platforms',
    companyLogo: 'https://logo.clearbit.com/jio.com',
    companyWebsite: 'https://jio.com',
    location: 'Navi Mumbai / Hyderabad, India',
    salary: '₹20,00,000 - ₹32,00,000 / yr',
    jobType: 'full_time',
    category: 'DevOps & Cloud',
    experienceLevel: 'mid',
    requiredSkills: ['Kubernetes', 'Go', '5G Core Protocols', 'OpenShift', 'Linux Networking', 'NFV'],
    tags: ['Telecom', '5G Edge', 'National Scale'],
    description: 'Build cloud-native 5G core network functions, edge AI inferencing clusters, and smart IoT device management backends.',
    jobUrl: 'https://jio.com/careers',
    applicantCount: 60,
    isActive: true
  },
  {
    title: 'AdTech Real-time Bidding & Big Data Architect',
    company: 'InMobi',
    companyLogo: 'https://logo.clearbit.com/inmobi.com',
    companyWebsite: 'https://inmobi.com',
    location: 'Bengaluru, India',
    salary: '₹28,00,000 - ₹45,00,000 / yr',
    jobType: 'full_time',
    category: 'AI & Data',
    experienceLevel: 'senior',
    requiredSkills: ['Java', 'C++', 'Aerospike', 'Kafka', 'Spark', 'Low-Latency Systems'],
    tags: ['AdTech', 'Real-Time Bidding', 'Unicorn'],
    description: 'Process sub-50ms ad auctions serving over 2 billion global users across mobile app inventory.',
    jobUrl: 'https://inmobi.com/company/careers',
    applicantCount: 39,
    isActive: true
  },
  {
    title: 'Senior SaaS Application Engineer (Ruby / React)',
    company: 'Freshworks',
    companyLogo: 'https://logo.clearbit.com/freshworks.com',
    companyWebsite: 'https://freshworks.com',
    location: 'Chennai / Bengaluru, India',
    salary: '₹22,00,000 - ₹36,00,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'mid',
    requiredSkills: ['Ruby on Rails', 'React', 'TypeScript', 'AWS', 'MySQL', 'Redis'],
    tags: ['Enterprise SaaS', 'Customer Success', 'Product Led'],
    description: 'Design omnichannel customer support automation tools, AI ticket triage bots, and customizable helpdesk portals.',
    jobUrl: 'https://freshworks.com/careers',
    applicantCount: 58,
    isActive: true
  },
  {
    title: 'Cloud Office Suite Developer (Java / WebAssembly)',
    company: 'Zoho',
    companyLogo: 'https://logo.clearbit.com/zoho.com',
    companyWebsite: 'https://zoho.com',
    location: 'Chennai / Tenkasi, India',
    salary: '₹14,00,000 - ₹24,00,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'mid',
    requiredSkills: ['Java', 'C++', 'WebAssembly', 'JavaScript', 'SQL', 'Document Parsers'],
    tags: ['Office Suite', 'Bootstrapped Giant', 'Deep Tech'],
    description: 'Work on collaborative spreadsheet calculation engines, offline document rendering via WASM, and proprietary database servers.',
    jobUrl: 'https://zoho.com/careers',
    applicantCount: 91,
    isActive: true
  },
  {
    title: 'Core UPI & Payments Gateway Engineer',
    company: 'Paytm',
    companyLogo: 'https://logo.clearbit.com/paytm.com',
    companyWebsite: 'https://paytm.com',
    location: 'Noida / Bengaluru, India',
    salary: '₹20,00,000 - ₹34,00,000 / yr',
    jobType: 'full_time',
    category: 'Backend',
    experienceLevel: 'mid',
    requiredSkills: ['Java', 'Spring Boot', 'MySQL', 'Redis', 'Distributed Systems', 'Security'],
    tags: ['FinTech', 'Soundbox', 'QR Payments'],
    description: 'Engineer high-reliability payment confirmation systems for millions of merchant Soundbox devices and wallet checkouts.',
    jobUrl: 'https://paytm.com/careers',
    applicantCount: 74,
    isActive: true
  },
  {
    title: 'Fintech Product Engineer (Investment Portfolios)',
    company: 'Groww',
    companyLogo: 'https://logo.clearbit.com/groww.in',
    companyWebsite: 'https://groww.in',
    location: 'Bengaluru, India',
    salary: '₹24,00,000 - ₹38,00,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'mid',
    requiredSkills: ['React', 'TypeScript', 'Go', 'Microservices', 'PostgreSQL', 'Redis'],
    tags: ['FinTech', 'Mutual Funds & Stocks', 'Fast Growing'],
    description: 'Build seamless onboarding journeys, SIP auto-debits, and live stock charts for 40M+ retail investors across India.',
    jobUrl: 'https://groww.in/careers',
    applicantCount: 103,
    isActive: true
  },
  {
    title: 'Hyperlocal Platform Architect (Node.js / React)',
    company: 'Urban Company',
    companyLogo: 'https://logo.clearbit.com/urbancompany.com',
    companyWebsite: 'https://urbancompany.com',
    location: 'Gurugram / Bengaluru, India',
    salary: '₹26,00,000 - ₹42,00,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'senior',
    requiredSkills: ['Node.js', 'React', 'MongoDB', 'Redis', 'Geospatial Indexing', 'Kafka'],
    tags: ['Home Services', 'Hyperlocal', 'Marketplace'],
    description: 'Architect slot booking engines, dynamic pricing algorithms, and professional partner training portals across 50+ cities.',
    jobUrl: 'https://urbancompany.com/careers',
    applicantCount: 47,
    isActive: true
  },
  {
    title: 'Quantitative Developer & Algorithmic Trading Lead',
    company: 'Goldman Sachs',
    companyLogo: 'https://logo.clearbit.com/goldmansachs.com',
    companyWebsite: 'https://goldmansachs.com',
    location: 'New York, NY / Bengaluru, India',
    salary: '$180,000 - $260,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'senior',
    requiredSkills: ['C++', 'Python', 'Low-Latency Linux', 'Financial Modeling', 'SQL', 'Multithreading'],
    tags: ['Investment Banking', 'Quant Trading', 'Wall Street'],
    description: 'Develop low-latency electronic market-making algorithms and high-throughput order routing platforms for global equities and derivatives.',
    jobUrl: 'https://goldmansachs.com/careers',
    applicantCount: 82,
    isActive: true
  },
  {
    title: 'Enterprise Cloud & Cybersecurity Architect',
    company: 'JPMorgan Chase',
    companyLogo: 'https://logo.clearbit.com/jpmorgan.com',
    companyWebsite: 'https://jpmorgan.com',
    location: 'Jersey City, NJ / Hyderabad, India',
    salary: '$165,000 - $230,000 / yr',
    jobType: 'full_time',
    category: 'Security & Web3',
    experienceLevel: 'senior',
    requiredSkills: ['Cybersecurity', 'AWS/Azure', 'Zero Trust', 'SIEM', 'Python', 'DevSecOps'],
    tags: ['Banking', 'Cybersecurity', 'Enterprise Cloud'],
    description: 'Safeguard trillions of dollars in daily asset transfers with modern cryptographic protocols, threat detection, and automated vulnerability remediations.',
    jobUrl: 'https://careers.jpmorgan.com',
    applicantCount: 53,
    isActive: true
  },
  {
    title: 'Financial Data Feed & Terminal Systems Engineer (C++ / Python)',
    company: 'Bloomberg',
    companyLogo: 'https://logo.clearbit.com/bloomberg.com',
    companyWebsite: 'https://bloomberg.com',
    location: 'New York, NY / London, UK',
    salary: '$170,000 - $240,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'senior',
    requiredSkills: ['C++', 'Python', 'Real-Time Data Feeds', 'TCP/IP Sockets', 'Distributed Systems'],
    tags: ['Bloomberg Terminal', 'Financial Data', 'High Reliability'],
    description: 'Build backend pipelines processing billions of market ticks per second powering the legendary Bloomberg Terminal for 350k+ financial leaders.',
    jobUrl: 'https://bloomberg.com/careers',
    applicantCount: 66,
    isActive: true
  },
  {
    title: 'Fixed Income & Risk Analytics Developer',
    company: 'Morgan Stanley',
    companyLogo: 'https://logo.clearbit.com/morganstanley.com',
    companyWebsite: 'https://morganstanley.com',
    location: 'New York, NY / Mumbai, India',
    salary: '$150,000 - $210,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'mid',
    requiredSkills: ['Java', 'Python', 'Spring Cloud', 'PostgreSQL', 'Risk Modeling', 'Angular/React'],
    tags: ['Investment Banking', 'Risk Management', 'FinTech'],
    description: 'Create real-time value-at-risk simulation calculators and stress testing platforms for global fixed income trading desks.',
    jobUrl: 'https://morganstanley.com/careers',
    applicantCount: 41,
    isActive: true
  },
  {
    title: 'Remote Full Stack WordPress & Gutenberg Specialist',
    company: 'Automattic',
    companyLogo: 'https://logo.clearbit.com/automattic.com',
    companyWebsite: 'https://automattic.com',
    location: 'Remote - Worldwide',
    salary: '$105,000 - $145,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'mid',
    requiredSkills: ['PHP', 'React', 'JavaScript', 'WordPress REST API', 'MySQL', 'CSS'],
    tags: ['Open Source', 'WordPress.com', 'Remote Pioneer'],
    description: 'Work on WordPress.com, WooCommerce extensions, and Gutenberg block editor features democratizing online publishing for millions.',
    jobUrl: 'https://automattic.com/work-with-us',
    applicantCount: 87,
    isActive: true
  },
  {
    title: 'Freelance Ruby on Rails & Hotwire Specialist',
    company: 'Basecamp',
    companyLogo: 'https://logo.clearbit.com/basecamp.com',
    companyWebsite: 'https://basecamp.com',
    location: 'Remote - Worldwide',
    salary: '$95 - $135 / hr',
    jobType: 'freelance',
    category: 'Engineering',
    experienceLevel: 'senior',
    requiredSkills: ['Ruby on Rails', 'Hotwire', 'Turbo', 'Stimulus.js', 'SQLite', 'TailwindCSS'],
    tags: ['Freelance', 'Hotwire', 'Bootstrapped'],
    description: 'Contract engagement for bespoke Rails plugins, Turbo frame optimizations, and offline caching patterns for modern project management.',
    jobUrl: 'https://basecamp.com/about/jobs',
    applicantCount: 36,
    isActive: true
  },
  {
    title: 'Remote Social Media Analytics Developer',
    company: 'Buffer',
    companyLogo: 'https://logo.clearbit.com/buffer.com',
    companyWebsite: 'https://buffer.com',
    location: 'Remote - Worldwide (4-Day Work Week)',
    salary: '$115,000 - $155,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'mid',
    requiredSkills: ['Node.js', 'React', 'GraphQL', 'MongoDB', 'Social Media APIs', 'AWS Lambda'],
    tags: ['4-Day Work Week', 'Remote Culture', 'Social Media'],
    description: 'Build multi-channel social media scheduling tools, sentiment analytics, and AI caption generators with transparent company culture.',
    jobUrl: 'https://buffer.com/journey',
    applicantCount: 145,
    isActive: true
  },
  {
    title: 'Senior Lightning Platform & Apex Architect',
    company: 'Salesforce',
    companyLogo: 'https://logo.clearbit.com/salesforce.com',
    companyWebsite: 'https://salesforce.com',
    location: 'San Francisco, CA / Hyderabad, India',
    salary: '$160,000 - $220,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'senior',
    requiredSkills: ['Apex', 'Lightning Web Components (LWC)', 'Java', 'Salesforce DX', 'SOQL', 'REST APIs'],
    tags: ['Enterprise CRM', 'Cloud Platform', 'Market Leader'],
    description: 'Scale multi-tenant CRM database layers, Einstein AI automations, and enterprise integration patterns for Fortune 500 customers.',
    jobUrl: 'https://salesforce.com/company/careers',
    applicantCount: 62,
    isActive: true
  },
  {
    title: 'Web Graphics & Creative Cloud Engine Developer (WebAssembly)',
    company: 'Adobe',
    companyLogo: 'https://logo.clearbit.com/adobe.com',
    companyWebsite: 'https://adobe.com',
    location: 'San Jose, CA / Noida, India / Remote',
    salary: '$160,000 - $225,000 / yr',
    jobType: 'full_time',
    category: 'Frontend',
    experienceLevel: 'senior',
    requiredSkills: ['C++', 'WebAssembly', 'WebGL/WebGPU', 'React', 'Image Processing', 'TypeScript'],
    tags: ['Photoshop Web', 'Creative Tech', 'Graphics'],
    description: 'Bring desktop-class Photoshop, Illustrator, and Firefly AI creative engines to modern web browsers using WebAssembly and WebGPU.',
    jobUrl: 'https://adobe.com/careers',
    applicantCount: 75,
    isActive: true
  },
  {
    title: 'GPU Compiler & Parallel Computing Engineer',
    company: 'Intel',
    companyLogo: 'https://logo.clearbit.com/intel.com',
    companyWebsite: 'https://intel.com',
    location: 'Santa Clara, CA / Bengaluru, India',
    salary: '$150,000 - $215,000 / yr',
    jobType: 'full_time',
    category: 'Engineering',
    experienceLevel: 'senior',
    requiredSkills: ['C++', 'LLVM Compiler', 'SYCL / oneAPI', 'GPU Architecture', 'SPIR-V', 'Performance Tuning'],
    tags: ['Semiconductor', 'Compilers', 'Hardware'],
    description: 'Design open standard LLVM compiler backends and oneAPI parallel programming libraries for Intel Arc GPUs and Gaudi AI accelerators.',
    jobUrl: 'https://jobs.intel.com',
    applicantCount: 34,
    isActive: true
  },
  {
    title: 'ROCm Open-Source AI Acceleration Engineer',
    company: 'AMD',
    companyLogo: 'https://logo.clearbit.com/amd.com',
    companyWebsite: 'https://amd.com',
    location: 'Austin, TX / Hyderabad, India',
    salary: '$155,000 - $220,000 / yr',
    jobType: 'full_time',
    category: 'AI & Data',
    experienceLevel: 'senior',
    requiredSkills: ['C++', 'ROCm', 'PyTorch', 'HIP Programming', 'GPU Drivers', 'Linux Kernel'],
    tags: ['AI Accelerators', 'ROCm', 'Open Source'],
    description: 'Develop open software stacks powering MI300X AI accelerators. Enable out-of-the-box PyTorch training for frontier multimodal models.',
    jobUrl: 'https://amd.com/en/corporate/careers',
    applicantCount: 43,
    isActive: true
  },
  {
    title: 'Secure Cloud Networking & Zero Trust Engineer',
    company: 'Cisco',
    companyLogo: 'https://logo.clearbit.com/cisco.com',
    companyWebsite: 'https://cisco.com',
    location: 'San Jose, CA / Bengaluru, India',
    salary: '$145,000 - $200,000 / yr',
    jobType: 'full_time',
    category: 'DevOps & Cloud',
    experienceLevel: 'senior',
    requiredSkills: ['Python', 'Go', 'SD-WAN', 'Zero Trust Architecture', 'BGP', 'Docker'],
    tags: ['Networking', 'Cybersecurity', 'Cloud WAN'],
    description: 'Engineer software-defined enterprise networking fabrics, automated VPN gateways, and threat intelligence telemetry systems.',
    jobUrl: 'https://cisco.com/c/en/us/about/careers',
    applicantCount: 52,
    isActive: true
  },
  {
    title: 'Database Cloud Services & Exadata Engineer',
    company: 'Oracle',
    companyLogo: 'https://logo.clearbit.com/oracle.com',
    companyWebsite: 'https://oracle.com',
    location: 'Austin, TX / Bengaluru, India',
    salary: '$150,000 - $210,000 / yr',
    jobType: 'full_time',
    category: 'Backend',
    experienceLevel: 'mid',
    requiredSkills: ['Java', 'C', 'Oracle DB', 'Linux Internals', 'Cloud Automation', 'Terraform'],
    tags: ['Oracle Cloud', 'Enterprise Database', 'OCI'],
    description: 'Maintain Autonomous Database cloud management control planes and automated patch management for critical enterprise databases.',
    jobUrl: 'https://oracle.com/corporate/careers',
    applicantCount: 50,
    isActive: true
  },
  {
    title: 'Quantum Computing & Hybrid Cloud Architect',
    company: 'IBM',
    companyLogo: 'https://logo.clearbit.com/ibm.com',
    companyWebsite: 'https://ibm.com',
    location: 'Yorktown Heights, NY / Bengaluru, India',
    salary: '$155,000 - $220,000 / yr',
    jobType: 'full_time',
    category: 'AI & Data',
    experienceLevel: 'senior',
    requiredSkills: ['Python', 'Qiskit', 'Quantum Algorithms', 'C++', 'Red Hat OpenShift', 'Linear Algebra'],
    tags: ['Quantum Computing', 'Qiskit', 'Hybrid Cloud'],
    description: 'Work with IBM Quantum System Two processors and design quantum-classical hybrid algorithms for materials science and cryptography.',
    jobUrl: 'https://ibm.com/careers',
    applicantCount: 37,
    isActive: true
  },
  {
    title: 'Recommendation Algorithm & Feed Ranking Engineer',
    company: 'ByteDance',
    companyLogo: 'https://logo.clearbit.com/bytedance.com',
    companyWebsite: 'https://bytedance.com',
    location: 'Singapore / San Jose, CA',
    salary: '$170,000 - $245,000 / yr',
    jobType: 'full_time',
    category: 'AI & Data',
    experienceLevel: 'senior',
    requiredSkills: ['C++', 'Python', 'Deep Learning', 'Real-time Ranking', 'Reinforcement Learning', 'Embedding Models'],
    tags: ['TikTok Algorithm', 'Recommendation Systems', 'High Scale'],
    description: 'Design world-class personalized recommendation engines and video understanding pipelines delivering engaging content in sub-10ms.',
    jobUrl: 'https://jobs.bytedance.com',
    applicantCount: 165,
    isActive: true
  },
  {
    title: 'Software Engineering Summer Intern (2026 Batch)',
    company: 'Google',
    companyLogo: 'https://logo.clearbit.com/google.com',
    companyWebsite: 'https://google.com',
    location: 'Bengaluru / Hyderabad, India / Mountain View, CA',
    salary: '₹1,00,000 / month Stipend',
    jobType: 'internship',
    category: 'Engineering',
    experienceLevel: 'fresher',
    requiredSkills: ['Data Structures & Algorithms', 'C++', 'Java', 'Python', 'Problem Solving'],
    tags: ['Internship', 'Mentorship', 'PPO Opportunity'],
    description: 'Work on real-world production systems across Google Search, Android, Chrome, or YouTube alongside dedicated technical mentors.',
    jobUrl: 'https://careers.google.com/students',
    applicantCount: 310,
    isActive: true
  },
  {
    title: 'Graduate Cloud Support & SDE Intern',
    company: 'Amazon',
    companyLogo: 'https://logo.clearbit.com/amazon.com',
    companyWebsite: 'https://amazon.com',
    location: 'Bengaluru / Chennai, India',
    salary: '₹80,000 / month Stipend',
    jobType: 'internship',
    category: 'Engineering',
    experienceLevel: 'fresher',
    requiredSkills: ['Java', 'Python', 'AWS Basics', 'Linux Command Line', 'Networking Basics'],
    tags: ['Internship', 'AWS Cloud', 'Fast Track'],
    description: 'Gain hands-on experience debugging cloud architectures, deploying microservices on ECS, and collaborating with global AWS solutions teams.',
    jobUrl: 'https://amazon.jobs/en/teams/internships-for-students',
    applicantCount: 220,
    isActive: true
  },
  {
    title: 'UX Design & Frontend Engineering Internship (Summer 2026)',
    company: 'Adobe',
    companyLogo: 'https://logo.clearbit.com/adobe.com',
    companyWebsite: 'https://adobe.com',
    location: 'Noida / Bengaluru, India',
    salary: '₹75,000 / month Stipend',
    jobType: 'internship',
    category: 'Frontend',
    experienceLevel: 'fresher',
    requiredSkills: ['React', 'JavaScript', 'HTML5/CSS3', 'Figma', 'UI Prototyping'],
    tags: ['Internship', 'UI/UX', 'Design Engineering'],
    description: 'Design and prototype creative tools and interactive web components for Adobe Express and Creative Cloud web ecosystems.',
    jobUrl: 'https://adobe.com/careers/university',
    applicantCount: 160,
    isActive: true
  }
];

/**
 * Seeds or refreshes the database with the curated predefined job postings
 */
async function seedIfEmpty() {
  try {
    const count = await JobPosting.countDocuments();
    
    // If the database has fewer than 60 jobs, sync all 72 curated postings
    if (count < 60) {
      console.log(`📡 Seeding/Updating database with all ${CURATED_JOBS.length} curated diverse job postings...`);
      
      // Upsert each curated job by (company + title) to preserve existing IDs and avoid duplicates
      for (const job of CURATED_JOBS) {
        await JobPosting.findOneAndUpdate(
          { company: job.company, title: job.title },
          { $set: job },
          { upsert: true, new: true, setDefaultsOnInsert: true }
        );
      }
      
      const updatedCount = await JobPosting.countDocuments();
      console.log(`✅ Successfully synced ${updatedCount} diverse predefined job postings across all categories.`);
      return true;
    }

    console.log(`📦 Database already contains ${count} job postings ready for application tracking.`);
    return false;
  } catch (error) {
    console.error('❌ JobPosting seed error:', error.message);
    return false;
  }
}

module.exports = { seedIfEmpty, CURATED_JOBS };
